version: "3.9"
services:
  nginx:
    image: nginx:1.22-alpine
    container_name: proxy_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_app
    deploy:
      replicas: 5
      condition: on-failure
    ports:
      - "3020:3020"

   